"""Add created_at and updated_at fields to Sale model

Revision ID: 083129680673
Revises: a6ec57bfb3f4
Create Date: 2024-11-20 16:20:41.300178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083129680673'
down_revision = 'a6ec57bfb3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
